hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/gsm8k/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: stablelm-2-12b
  - estimators: default_plus_spline_stablelm12b
  - stat_calculators: spline_calculators
  - base_processing_gsm8k
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: false
task: qa

dataset: ['LM-Polygraph/gsm8k', 'continuation']
text_column: input
label_column: output
train_split: train
eval_split: test
few_shot_prompt: null
max_new_tokens: 256
load_from_disk: false
trust_remote_code: true
size: 10000
generation_params:
  stop_strings:
    - "\n"



generation_metrics:
  - name: AccuracyMetric

subsample_eval_dataset: 2000
ignore_exceptions: false
batch_size: 1

seed:
  - 1
