hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/coqa/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: stablelm-2-12b
  - estimators: default_plus_spline_stablelm12b
  - stat_calculators: spline_calculators
  - base_processing_coqa
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: false
task: qa

dataset: ['LM-polygraph/coqa', 'continuation']
text_column: input
label_column: output
train_split: train
eval_split: test
n_shot: 0
few_shot_split: train
few_shot_prompt: null
trust_remote_code: true
size: null
max_new_tokens: 20
load_from_disk: false
generation_params:
  stop_strings:
    - "\n"

generation_metrics:
  - name: AccuracyMetric
  - name: AlignScore
    kwargs:
      target_is_claims: true

subsample_eval_dataset: -1
ignore_exceptions: false
batch_size: 2

seed:
  - 1