hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/triviaqa/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: mistral-7b-v0.2
  - estimators: default_plus_spline_mistral7b
  - stat_calculators: spline_calculators
  - base_processing_triviaqa
  - _self_

generation_metrics:
  - name: AccuracyMetric
  - name: AlignScore
    kwargs:
      target_is_claims: true

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: false
task: qa

dataset: ['LM-Polygraph/triviaqa', 'continuation']
text_column: input
label_column: output
train_split: train
eval_split: test
max_new_tokens: 20
load_from_disk: false
multiref: true
trust_remote_code: false
size: 10000
generation_params:
  stop_strings:
    - "\n"

subsample_eval_dataset: -1
ignore_exceptions: false
batch_size: 2

seed:
  - 1
